# Generated by Django 5.2.15 on 2026-06-17 16:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('doctors', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Reservasi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tanggal_reservasi', models.DateField(verbose_name='Tanggal Reservasi')),
                ('keluhan', models.TextField(blank=True, verbose_name='Keluhan')),
                ('status_reservasi', models.CharField(choices=[('AKTIF', 'Aktif'), ('SELESAI', 'Selesai'), ('DIBATALKAN', 'Dibatalkan')], default='AKTIF', max_length=15, verbose_name='Status')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Dibuat pada')),
                ('jadwal', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reservasi', to='doctors.jadwaldokter', verbose_name='Jadwal Dokter')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservasi', to=settings.AUTH_USER_MODEL, verbose_name='Pasien')),
            ],
            options={
                'verbose_name': 'Reservasi',
                'verbose_name_plural': 'Reservasi',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Antrian',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomor_antrian', models.PositiveIntegerField(verbose_name='Nomor Antrean')),
                ('status', models.CharField(choices=[('MENUNGGU', 'Menunggu'), ('DIPANGGIL', 'Dipanggil'), ('SELESAI', 'Selesai'), ('DIBATALKAN', 'Dibatalkan')], default='MENUNGGU', max_length=15, verbose_name='Status')),
                ('waktu_dipanggil', models.DateTimeField(blank=True, null=True, verbose_name='Waktu Dipanggil')),
                ('estimasi_menit', models.PositiveIntegerField(default=0, verbose_name='Estimasi Tunggu (menit)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Dibuat pada')),
                ('reservasi', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='antrian', to='reservations.reservasi', verbose_name='Reservasi')),
            ],
            options={
                'verbose_name': 'Antrean',
                'verbose_name_plural': 'Antrean',
                'ordering': ['nomor_antrian'],
            },
        ),
    ]
