# Generated by Django 5.2.15 on 2026-06-17 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('judul', models.CharField(max_length=200, verbose_name='Judul')),
                ('deskripsi', models.TextField(blank=True, verbose_name='Deskripsi')),
                ('gambar', models.ImageField(upload_to='banners/', verbose_name='Gambar')),
                ('aktif', models.BooleanField(default=True, verbose_name='Aktif')),
                ('urutan', models.PositiveIntegerField(default=0, verbose_name='Urutan')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Dibuat pada')),
            ],
            options={
                'verbose_name': 'Banner',
                'verbose_name_plural': 'Banner',
                'ordering': ['urutan', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Klinik',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=200, verbose_name='Nama Tempat Praktik')),
                ('alamat', models.TextField(verbose_name='Alamat')),
                ('jam_operasional', models.CharField(max_length=200, verbose_name='Jam Operasional')),
                ('telepon', models.CharField(max_length=30, verbose_name='Telepon')),
                ('deskripsi', models.TextField(blank=True, verbose_name='Deskripsi')),
                ('aktif', models.BooleanField(default=True, verbose_name='Aktif')),
            ],
            options={
                'verbose_name': 'Tempat Praktik',
                'verbose_name_plural': 'Tempat Praktik',
                'ordering': ['nama'],
            },
        ),
    ]
