# Generated by Django 5.2.15 on 2026-06-17 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='klinik',
            name='latitude',
            field=models.FloatField(default=-6.3503, verbose_name='Latitude'),
        ),
        migrations.AddField(
            model_name='klinik',
            name='longitude',
            field=models.FloatField(default=106.8643, verbose_name='Longitude'),
        ),
        migrations.AddField(
            model_name='klinik',
            name='tipe',
            field=models.CharField(choices=[('Klinik', 'Klinik / Tempat Praktik'), ('Apotek', 'Apotek / Farmasi')], default='Klinik', max_length=20, verbose_name='Tipe Tempat'),
        ),
    ]
