# Generated by Django 5.2.15 on 2026-06-17 16:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='JenisLayanan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_layanan', models.CharField(max_length=100, verbose_name='Nama Layanan')),
                ('deskripsi', models.TextField(blank=True, verbose_name='Deskripsi')),
                ('aktif', models.BooleanField(default=True, verbose_name='Aktif')),
            ],
            options={
                'verbose_name': 'Jenis Layanan',
                'verbose_name_plural': 'Jenis Layanan',
                'ordering': ['nama_layanan'],
            },
        ),
        migrations.CreateModel(
            name='Dokter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=150, verbose_name='Nama Dokter')),
                ('foto', models.ImageField(blank=True, null=True, upload_to='dokter/', verbose_name='Foto')),
                ('aktif', models.BooleanField(default=True, verbose_name='Aktif')),
                ('klinik', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='dokter', to='core.klinik', verbose_name='Klinik / Tempat Praktik')),
                ('jenis_layanan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='dokter', to='doctors.jenislayanan', verbose_name='Jenis Layanan')),
            ],
            options={
                'verbose_name': 'Dokter',
                'verbose_name_plural': 'Dokter',
                'ordering': ['nama'],
            },
        ),
        migrations.CreateModel(
            name='JadwalDokter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hari', models.CharField(choices=[('Senin', 'Senin'), ('Selasa', 'Selasa'), ('Rabu', 'Rabu'), ('Kamis', 'Kamis'), ('Jumat', 'Jumat'), ('Sabtu', 'Sabtu'), ('Minggu', 'Minggu')], max_length=10, verbose_name='Hari')),
                ('jam_mulai', models.TimeField(verbose_name='Jam Mulai')),
                ('jam_selesai', models.TimeField(verbose_name='Jam Selesai')),
                ('kuota_harian', models.PositiveIntegerField(default=20, verbose_name='Kuota Harian')),
                ('aktif', models.BooleanField(default=True, verbose_name='Aktif')),
                ('dokter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jadwal', to='doctors.dokter', verbose_name='Dokter')),
            ],
            options={
                'verbose_name': 'Jadwal Dokter',
                'verbose_name_plural': 'Jadwal Dokter',
                'unique_together': {('dokter', 'hari', 'jam_mulai')},
            },
        ),
    ]
