# Generated by Django 5.2.15 on 2026-06-17 16:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('doctors', '0001_initial'),
        ('reservations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RiwayatKunjungan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('catatan', models.TextField(blank=True, verbose_name='Catatan')),
                ('tanggal_kunjungan', models.DateField(verbose_name='Tanggal Kunjungan')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Dibuat pada')),
                ('dokter', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='riwayat_kunjungan', to='doctors.dokter', verbose_name='Dokter')),
                ('reservasi', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='riwayat', to='reservations.reservasi', verbose_name='Reservasi')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='riwayat_kunjungan', to=settings.AUTH_USER_MODEL, verbose_name='Pasien')),
            ],
            options={
                'verbose_name': 'Riwayat Kunjungan',
                'verbose_name_plural': 'Riwayat Kunjungan',
                'ordering': ['-tanggal_kunjungan'],
            },
        ),
    ]
